name: Check licenses

on:
  pull_request:
    branches:
      - master

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check license-checker CSV file without headers
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          external: 'npm-license-checker.csv'
          external-format: 'csv'
          external-options: '{:skip-header true}'
          fail: 'StrongCopyleft,NetworkCopyleft,Other,Error'
          fails-only: true
          exclude: 'evolv.*'
          exclude-license: '(?i)copyright'
          totals: true
          verbose: 1
          github-token: ${{ secrets.GH_TOKEN }}


