name: Cherry Pick Commits

on:
  pull_request:
    branches: 
      - master
    types: [closed]

jobs:
  cherry-pick:
    name: Cherry Pick Commits
    if: ${{github.event.pull_request.merged}} == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Cherry Picker
        uses: evolv-ai/github-actions/cherry-picker@v6
        id: cherry-picker
        with:
          token: "${{ secrets.GH_TOKEN }}"
          pull_number: ${{ github.event.pull_request.number }}
          slack_webhook: ${{ secrets.CHERRY_PICK_SLACK_WEBHOOK }}
