name: Create Staging Deployment from Release Tag

on:
  push:
    tags:
      - 'release/*'

jobs:
  deploy:
    name: Deploy to Staging

    runs-on: ubuntu-latest

    steps:
      - name: Get the tag
        id: get_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.REPOSITORY_ACCESS_TOKEN }}"
          ref: ${{ steps.get_tag.outputs.TAG }}
          description: ${{ steps.get_tag.outputs.TAG }}
          environment: staging
